services:

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak25
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-providers:/opt/keycloak/providers
      - ./keycloak-import:/opt/keycloak/data/import
    networks:
      - demo-network

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak
    restart: on-failure
    networks:
      - demo-network

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak
      - api-service
    restart: on-failure
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge