spring.cloud.gateway.server.webflux.routes[0].id=api-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://api-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/**

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/demo/protocol/openid-connect/certs